## Tensors
Tensors are a specialized data structure similar to arrays and matrices. Tensors run on GPUs and other hardware accelerators. Tensors are optimized for automatic differentiation.

In [3]:
import torch
import numpy as np

### Initialize a Tensor

In [12]:
# Method 1: From data
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

# Method 2: From NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

# Method 3: Ones tensor, zeros tensor
x_ones = torch.ones_like(x_data) # it will retain the properties of x_data
x_zeros = torch.zeros_like(x_data)
print(x_zeros)
print(x_ones)

# Method 4: Random tensor
x_rand_float = torch.rand_like(x_data, dtype=torch.float)
print(x_rand_float)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[0, 0],
        [0, 0]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.5473, 0.7935],
        [0.9194, 0.7955]])


In [15]:
# Create a tensor of a particular shape
shape = (2,3,)
ones_tensor = torch.ones(shape)
print(ones_tensor)
print("shape=", ones_tensor.shape)
print("data type=", ones_tensor.dtype)
print("device=", ones_tensor.device)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
shape= torch.Size([2, 3])
data type= torch.float32
device= cpu


### Operations on Tensors

In [17]:
# Move to GPU
if torch.cuda.is_available():
    print("It's available!")
    tensor = ones_tensor.to('cuda')

In [29]:
# Slicing
tensor = torch.rand(4,4)
print(tensor)
print("\n")

print("First row = ", tensor[0])
print("First column = ", tensor[:, 0])
print("Last column = ", tensor[:, 3])
print("\n")

print("Last two columns = ", tensor[:, 2:4])
print("Middle two rows = ", tensor[1:3])



tensor([[0.2348, 0.4610, 0.0095, 0.6881],
        [0.4633, 0.5565, 0.5750, 0.9090],
        [0.4819, 0.0969, 0.1538, 0.6061],
        [0.7819, 0.5194, 0.1380, 0.7683]])


First row =  tensor([0.2348, 0.4610, 0.0095, 0.6881])
First column =  tensor([0.2348, 0.4633, 0.4819, 0.7819])
Last column =  tensor([0.6881, 0.9090, 0.6061, 0.7683])


Last two columns =  tensor([[0.0095, 0.6881],
        [0.5750, 0.9090],
        [0.1538, 0.6061],
        [0.1380, 0.7683]])
Middle two rows =  tensor([[0.4633, 0.5565, 0.5750, 0.9090],
        [0.4819, 0.0969, 0.1538, 0.6061]])


In [33]:
# Concatenate

# Vertical Stacking
t1 = torch.concat([tensor, tensor], dim=0)
print(t1)
print("\n")

# Horizontal stacking
t2 = torch.concat([tensor, tensor], dim=1)
print(t2)

tensor([[0.2348, 0.4610, 0.0095, 0.6881],
        [0.4633, 0.5565, 0.5750, 0.9090],
        [0.4819, 0.0969, 0.1538, 0.6061],
        [0.7819, 0.5194, 0.1380, 0.7683],
        [0.2348, 0.4610, 0.0095, 0.6881],
        [0.4633, 0.5565, 0.5750, 0.9090],
        [0.4819, 0.0969, 0.1538, 0.6061],
        [0.7819, 0.5194, 0.1380, 0.7683]])


tensor([[0.2348, 0.4610, 0.0095, 0.6881, 0.2348, 0.4610, 0.0095, 0.6881],
        [0.4633, 0.5565, 0.5750, 0.9090, 0.4633, 0.5565, 0.5750, 0.9090],
        [0.4819, 0.0969, 0.1538, 0.6061, 0.4819, 0.0969, 0.1538, 0.6061],
        [0.7819, 0.5194, 0.1380, 0.7683, 0.7819, 0.5194, 0.1380, 0.7683]])


In [36]:
# Arithmetic Operations

# Matrix Multiplication
print("Original tensor = ", tensor)
print("Transposed tensor = ", tensor.T)
y1 = tensor @ tensor.T
print("y1 = ", y1)
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
y3 = torch.matmul(tensor, tensor.T, out=y3)

Original tensor =  tensor([[0.2348, 0.4610, 0.0095, 0.6881],
        [0.4633, 0.5565, 0.5750, 0.9090],
        [0.4819, 0.0969, 0.1538, 0.6061],
        [0.7819, 0.5194, 0.1380, 0.7683]])
Transposed tensor =  tensor([[0.2348, 0.4633, 0.4819, 0.7819],
        [0.4610, 0.5565, 0.0969, 0.5194],
        [0.0095, 0.5750, 0.1538, 0.1380],
        [0.6881, 0.9090, 0.6061, 0.7683]])
y1 =  tensor([[0.7412, 0.9962, 0.5763, 0.9530],
        [0.9962, 1.6812, 0.9165, 1.4290],
        [0.5763, 0.9165, 0.6326, 0.9140],
        [0.9530, 1.4290, 0.9140, 1.4905]])


In [39]:
# Element wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[5.5151e-02, 2.1255e-01, 8.9646e-05, 4.7343e-01],
        [2.1461e-01, 3.0972e-01, 3.3062e-01, 8.2622e-01],
        [2.3223e-01, 9.3903e-03, 2.3649e-02, 3.6735e-01],
        [6.1144e-01, 2.6975e-01, 1.9052e-02, 5.9027e-01]])

In [41]:
# Single element tensors
s1 = tensor.sum()
print(s1)
print(type(s1))

s1_item = s1.item()
print(s1_item)
print(type(s1_item))

tensor(7.4435)
<class 'torch.Tensor'>
7.443466663360596
<class 'float'>


In [42]:
# In place operations
# Denoted by _
print(tensor)
tensor.add_(1)
print(tensor)

tensor([[0.2348, 0.4610, 0.0095, 0.6881],
        [0.4633, 0.5565, 0.5750, 0.9090],
        [0.4819, 0.0969, 0.1538, 0.6061],
        [0.7819, 0.5194, 0.1380, 0.7683]])
tensor([[1.2348, 1.4610, 1.0095, 1.6881],
        [1.4633, 1.5565, 1.5750, 1.9090],
        [1.4819, 1.0969, 1.1538, 1.6061],
        [1.7819, 1.5194, 1.1380, 1.7683]])


In [44]:
# Tensor to Numpy
t = torch.ones(5)
print(t)
print(type(t))

n = t.numpy()
print(n)
print(type(n))

# Any change in t reflects in n
t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [45]:
# Numpy to Tensor
n = np.ones(1)
print(n)
print(type(n))

t = torch.from_numpy(n)
print(t)
print(type(t))

np.add(n, 1, out=n)
print(t)
print(n)

[1.]
<class 'numpy.ndarray'>
tensor([1.], dtype=torch.float64)
<class 'torch.Tensor'>
tensor([2.], dtype=torch.float64)
[2.]
